"""Integracion completa de modelos hanna y restaurante

Revision ID: 08705e9f4007
Revises: 
Create Date: 2026-04-04 17:28:36.319292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08705e9f4007'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurante_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('table_restaurant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'restaurante', ['restaurante_id'], ['id'])
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('table_restaurant_id_fkey'), 'restaurante', ['restaurant_id'], ['id'])
        batch_op.drop_column('restaurante_id')

    # ### end Alembic commands ###
