"""modelos restaurante y reserva finales

Revision ID: 09500a4346d2
Revises: 9694439e2ede
Create Date: 2026-04-02 02:35:57.172020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09500a4346d2'
down_revision = '9694439e2ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurante_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_mesa', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('hora', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('num_personas', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('estado', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('origen', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('notas', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=False))
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'restaurante', ['restaurante_id'], ['id'])
        batch_op.drop_column('fecha_reserva')

    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('capacidad_total', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.drop_column('capacidad_total')
        batch_op.drop_column('telefono')
        batch_op.drop_column('direccion')

    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_reserva', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('notas')
        batch_op.drop_column('origen')
        batch_op.drop_column('estado')
        batch_op.drop_column('num_personas')
        batch_op.drop_column('hora')
        batch_op.drop_column('fecha')
        batch_op.drop_column('id_mesa')
        batch_op.drop_column('restaurante_id')

    # ### end Alembic commands ###
