"""empty message

Revision ID: 0df963bd27bf
Revises: 8c4162908714
Create Date: 2026-03-31 01:51:38.655124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df963bd27bf'
down_revision = '8c4162908714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=120), nullable=False),
    sa.Column('fecha_reserva', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    # ### end Alembic commands ###
