"""add_hours_to_restaurant

Revision ID: 23139428d53a
Revises: a9f63598acc9
Create Date: 2026-04-12 22:40:13.435834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23139428d53a'
down_revision = 'a9f63598acc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opening_time', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('closing_time', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.drop_column('closing_time')
        batch_op.drop_column('opening_time')

    # ### end Alembic commands ###
