"""empty message

Revision ID: 37145eaaecd8
Revises: 9d5ec3b1c230
Create Date: 2026-03-27 22:38:50.110855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37145eaaecd8'
down_revision = '9d5ec3b1c230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
