"""empty message

Revision ID: 38c2562dbfa4
Revises: 
Create Date: 2026-04-07 21:09:19.728719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c2562dbfa4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitud', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('longitud', sa.String(length=200), nullable=True))

    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitud', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('longitud', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.drop_column('longitud')
        batch_op.drop_column('latitud')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('longitud')
        batch_op.drop_column('latitud')

    # ### end Alembic commands ###
