"""add_foto_and_desc_to_menu

Revision ID: 48c78717a525
Revises: 23139428d53a
Create Date: 2026-04-13 01:15:21.542934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c78717a525'
down_revision = '23139428d53a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('descripcion', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('descripcion')
        batch_op.drop_column('foto')

    # ### end Alembic commands ###
