"""reset_develop

Revision ID: 4b2488fa8469
Revises: 
Create Date: 2026-04-04 03:45:52.316168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2488fa8469'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('gerente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('restaurante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('capacidad_total', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('id_mesa', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.String(length=20), nullable=False),
    sa.Column('hora', sa.String(length=10), nullable=False),
    sa.Column('num_personas', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('origen', sa.String(length=50), nullable=False),
    sa.Column('notas', sa.String(length=250), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('restaurante_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reservation')
    op.drop_table('host')
    op.drop_table('table')
    op.drop_table('waitlist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('check_in_time', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('estimated_time', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('waiting_state', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('waitlist_pkey')),
    sa.UniqueConstraint('check_in_time', name=op.f('waitlist_check_in_time_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('customer_id', name=op.f('waitlist_customer_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('estimated_time', name=op.f('waitlist_estimated_time_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('waiting_state', name=op.f('waitlist_waiting_state_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_number', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('table_pkey')),
    sa.UniqueConstraint('capacity', name=op.f('table_capacity_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('status', name=op.f('table_status_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('table_number', name=op.f('table_table_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('host',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('special_notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('total_visits', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_visit', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('host_pkey')),
    sa.UniqueConstraint('email', name=op.f('host_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('reservation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('table_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('reservation_time', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('reservation_date', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('reservation_pkey')),
    sa.UniqueConstraint('customer_id', name=op.f('reservation_customer_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('reservation_date', name=op.f('reservation_reservation_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('reservation_time', name=op.f('reservation_reservation_time_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('state', name=op.f('reservation_state_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('table_id', name=op.f('reservation_table_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('item_venta')
    op.drop_table('venta')
    op.drop_table('reserva')
    op.drop_table('menu')
    op.drop_table('restaurante')
    op.drop_table('owner')
    op.drop_table('gerente')
    op.drop_table('clients')
    # ### end Alembic commands ###
