"""empty message

Revision ID: 507784aa57fb
Revises: 09500a4346d2
Create Date: 2026-04-04 03:26:56.543538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507784aa57fb'
down_revision = '09500a4346d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('rol', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empleado')
    # ### end Alembic commands ###
