"""empty message

Revision ID: 6480ae8b343f
Revises: 0763d677d453
Create Date: 2026-03-24 00:13:15.878122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6480ae8b343f'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('special_notes', sa.String(length=500), nullable=False),
    sa.Column('total_visits', sa.Integer(), nullable=False),
    sa.Column('last_visit', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=120), nullable=False),
    sa.Column('table_id', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('reservation_time', sa.String(length=120), nullable=False),
    sa.Column('reservation_date', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id'),
    sa.UniqueConstraint('reservation_date'),
    sa.UniqueConstraint('reservation_time'),
    sa.UniqueConstraint('state'),
    sa.UniqueConstraint('table_id')
    )
    op.create_table('table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.String(length=120), nullable=False),
    sa.Column('capacity', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capacity'),
    sa.UniqueConstraint('status'),
    sa.UniqueConstraint('table_number')
    )
    op.create_table('waitlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=120), nullable=False),
    sa.Column('check_in_time', sa.String(length=120), nullable=False),
    sa.Column('estimated_time', sa.String(length=120), nullable=False),
    sa.Column('waiting_state', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('check_in_time'),
    sa.UniqueConstraint('customer_id'),
    sa.UniqueConstraint('estimated_time'),
    sa.UniqueConstraint('waiting_state')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waitlist')
    op.drop_table('table')
    op.drop_table('reservation')
    op.drop_table('host')
    # ### end Alembic commands ###
