"""empty message

Revision ID: 74303a226ee4
Revises: 0763d677d453
Create Date: 2026-03-22 21:08:52.587369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74303a226ee4'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('email')
    )
    op.create_table('detalle_venta',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_plato', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('menu',
    sa.Column('id_plato', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('id_restaurante', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_plato')
    )
    op.create_table('reserva',
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_mesa', sa.Integer(), nullable=False),
    sa.Column('id_restaurante', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('num_personas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    op.create_table('restaurante',
    sa.Column('id_restaurante', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('capacidad_total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_restaurante')
    )
    op.create_table('venta',
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('mesa',
    sa.Column('id_mesa', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('id_restaurante', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_restaurante'], ['restaurante.id_restaurante'], ),
    sa.PrimaryKeyConstraint('id_mesa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mesa')
    op.drop_table('venta')
    op.drop_table('restaurante')
    op.drop_table('reserva')
    op.drop_table('menu')
    op.drop_table('detalle_venta')
    op.drop_table('cliente')
    # ### end Alembic commands ###
