"""vincular_ventas_y_reservas_opcional

Revision ID: 81ee00c244d0
Revises: 0df963bd27bf
Create Date: 2026-03-31 04:01:28.478764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ee00c244d0'
down_revision = '0df963bd27bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'clients', ['cliente_id'], ['id'])
        batch_op.drop_column('nombre_cliente')

    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'clients', ['cliente_id'], ['id'])
        batch_op.drop_column('reserva_id')
        batch_op.drop_column('cliente')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('reserva_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cliente_id')

    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_cliente', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###
