"""empty message

Revision ID: 848c92658642
Revises: 
Create Date: 2026-04-09 00:25:26.129678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848c92658642'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('latitud', sa.String(length=200), nullable=True),
    sa.Column('longitud', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gerente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('restaurante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('capacidad_total', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('latitud', sa.String(length=200), nullable=True),
    sa.Column('longitud', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hostess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('special_notes', sa.String(length=500), nullable=True),
    sa.Column('total_visits', sa.Integer(), nullable=True),
    sa.Column('last_visit', sa.String(length=50), nullable=True),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('id_mesa', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.String(length=20), nullable=False),
    sa.Column('hora', sa.String(length=10), nullable=False),
    sa.Column('num_personas', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('origen', sa.String(length=50), nullable=False),
    sa.Column('notas', sa.String(length=250), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('restaurante_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waitlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=False),
    sa.Column('estimated_wait', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_venta')
    op.drop_table('waitlist')
    op.drop_table('venta')
    op.drop_table('table')
    op.drop_table('reserva')
    op.drop_table('menu')
    op.drop_table('hostess')
    op.drop_table('restaurante')
    op.drop_table('user')
    op.drop_table('owner')
    op.drop_table('gerente')
    op.drop_table('empleado')
    op.drop_table('clients')
    # ### end Alembic commands ###
