"""empty message

Revision ID: 8bd7f7918f9a
Revises: 7351e0d3f813
Create Date: 2026-03-27 01:58:14.211415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd7f7918f9a'
down_revision = '7351e0d3f813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu')
    op.drop_table('restaurante')
    # ### end Alembic commands ###
