"""empty message

Revision ID: a9f63598acc9
Revises: eed41f616808
Create Date: 2026-04-09 20:36:52.100522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f63598acc9'
down_revision = 'eed41f616808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
