"""creando tabla gerente y user

Revision ID: bc66aba2bb7f
Revises: 
Create Date: 2026-03-23 20:25:24.999930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc66aba2bb7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gerente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('clave', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mesa')
    op.drop_table('detalle_venta')
    op.drop_table('reserva')
    op.drop_table('menu')
    op.drop_table('restaurante')
    op.drop_table('venta')
    op.drop_table('cliente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_cliente', name=op.f('cliente_pkey')),
    sa.UniqueConstraint('email', name=op.f('cliente_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('venta',
    sa.Column('id_venta', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metodo_pago', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('id_reserva', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_venta', name=op.f('venta_pkey'))
    )
    op.create_table('restaurante',
    sa.Column('id_restaurante', sa.INTEGER(), server_default=sa.text("nextval('restaurante_id_restaurante_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('capacidad_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_restaurante', name='restaurante_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('menu',
    sa.Column('id_plato', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('id_restaurante', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_plato', name=op.f('menu_pkey'))
    )
    op.create_table('reserva',
    sa.Column('id_reserva', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_mesa', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_restaurante', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('hora', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('num_personas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_reserva', name=op.f('reserva_pkey'))
    )
    op.create_table('detalle_venta',
    sa.Column('id_detalle', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_venta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_plato', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_detalle', name=op.f('detalle_venta_pkey'))
    )
    op.create_table('mesa',
    sa.Column('id_mesa', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('capacidad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_restaurante', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_restaurante'], ['restaurante.id_restaurante'], name=op.f('mesa_id_restaurante_fkey')),
    sa.PrimaryKeyConstraint('id_mesa', name=op.f('mesa_pkey'))
    )
    op.drop_table('gerente')
    # ### end Alembic commands ###
