"""empty message

Revision ID: d0fb6aaea9e9
Revises: 08705e9f4007
Create Date: 2026-04-04 19:20:43.320289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0fb6aaea9e9'
down_revision = '08705e9f4007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostess', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_visits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_visit', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostess', schema=None) as batch_op:
        batch_op.drop_column('last_visit')
        batch_op.drop_column('total_visits')

    # ### end Alembic commands ###
