"""add_relations_to_reserva

Revision ID: d300b7c5271c
Revises: 3aa273e246b1
Create Date: 2026-03-28 21:37:02.991303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd300b7c5271c'
down_revision = '3aa273e246b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurante_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'restaurante', ['restaurante_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('restaurante_id')

    # ### end Alembic commands ###
